version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.27.0-20250101
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:4.27.0-20250101
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test-results:/app/test-results:rw  # Added explicit read-write permission
    depends_on:
      - chrome
      - selenium-hub
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge