
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"  # Selenium Grid Hub port
    environment:
      - SE_OPTS=--log-level INFO  # Removed redundant options
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

  selenium-node:
    image: selenium/node-chrome:latest  # Use browser-specific image
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"  # VNC port
      - "7900"  # noVNC port
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid
    deploy:
      replicas: 13  # Scale to 13 nodes
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g

networks:
  selenium-grid:
    external: true  # Ensure this matches the pre-created network name
