version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.27.0-20250101
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_TIMEOUT=300
      - GRID_BROWSER_TIMEOUT=300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - selenium-grid
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  chrome:
    image: selenium/node-chrome:4.27.0-20250101
    shm_size: '2g'
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_START_XVFB=false
    networks:
      - selenium-grid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  firefox:
    image: selenium/node-firefox:4.27.0-20250101
    shm_size: '2g'
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_START_XVFB=false
    networks:
      - selenium-grid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
    user: testuser
    volumes:
      - .:/app
      - ./test-results:/app/test-results
    environment:
      - PYTHONUNBUFFERED=1
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub
      - RUN_LOCALLY=false
      - PYTEST_ADDOPTS=--dist=loadfile -n auto
      - TEST_RESULTS_DIR=/app/test-results
    depends_on:
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_started
      firefox:
        condition: service_started
    networks:
      - selenium-grid
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

networks:
  selenium-grid:
    external: true