version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.27.0-20250101
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:4.27.0-20250101
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_START_XVFB=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-hub:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - selenium-grid

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-runner
    volumes:
      - .:/app:ro
      - ./test-results:/app/test-results:rw
      - /tmp:/tmp:rw
    environment:
      - PYTHONPATH=/app
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
      - DISPLAY=:99
    depends_on:
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_healthy
    networks:
      - selenium-grid
    shm_size: 2g
    restart: on-failure

networks:
  selenium-grid:
    name: selenium-grid
    driver: bridge