name: Selenium Grid Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Add permissions block
permissions:
  contents: read
  issues: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        mkdir -p test-results

    - name: Set up Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Clean up existing Docker resources
      run: |
        docker system prune -af
        docker network prune -f
        docker compose down --remove-orphans || true

    - name: Create Selenium Grid Network
      run: |
        docker network create selenium-grid || true

    - name: Start Selenium Grid
      run: |
        docker compose up -d selenium-hub chrome
        
        # Enhanced wait mechanism for Selenium Grid
        echo "Waiting for Selenium Grid to be ready..."
        max_attempts=20  # Increased wait time
        attempt=0
        
        while [ $attempt -lt $max_attempts ]; do
          if curl -s http://localhost:4444/wd/hub/status > /dev/null; then
            echo "Selenium Grid is ready!"
            break
          fi
          
          echo "Waiting... (attempt $((attempt+1))/$max_attempts)"
          sleep 10  # Increased sleep time
          attempt=$((attempt+1))
        done
        
        if [ $attempt -eq $max_attempts ]; then
          echo "Selenium Grid failed to start"
          docker compose logs
          exit 1
        fi

    - name: Run tests
      run: |
        mkdir -p test-results
        docker compose run --rm test-runner

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results
        retention-days: 5

    - name: Print logs on failure
      if: failure()
      run: |
        echo "Selenium Hub Logs:"
        docker compose logs selenium-hub
        echo -e "\nChrome Node Logs:"
        docker compose logs chrome
        echo -e "\nTest Runner Logs:"
        docker compose logs test-runner

    - name: Cleanup
      if: always()
      run: |
        docker compose down --remove-orphans
        docker network rm selenium-grid || true
        docker system prune -af

    - name: Create GitHub Issue on Failure
      if: failure()
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo;
          try {
            await github.rest.issues.create({
              owner,
              repo,
              title: 'Selenium Grid Test Failure in Workflow',
              body: `### Workflow Failure Details

              **Workflow Run:** ${context.runId}
              **Branch:** ${context.ref}
              **Event:** ${context.eventName}

              Automated test run failed. Please review the workflow logs for more details.

              :warning: Automatic notification generated by GitHub Actions`
            });
          } catch (error) {
            console.error('Failed to create issue:', error);
          }

    - name: Slack Notification
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}