name: Selenium Grid Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'sanity'
        type: choice
        options:
          - sanity
          - regression
          - all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        mkdir -p test-results

    - name: Set up Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Start Selenium Grid
      run: |
        docker network create selenium-grid || true
        docker compose up -d selenium-hub chrome
        
        # Wait for Grid to be ready
        timeout 60s bash -c 'until curl -s http://localhost:4444/wd/hub/status > /dev/null; do sleep 2; done'

    - name: Run tests
      run: |
        docker compose run --rm test-runner pytest -v tests/ui/ --html=test-results/report.html

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results

    - name: Print logs on failure
      if: failure()
      run: docker compose logs

    - name: Cleanup
      if: always()
      run: |
        docker compose down
        docker network rm selenium-grid || true