name: Selenium Grid Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        mkdir -p test-results

    - name: Set up Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Remove existing Selenium Grid network
      run: |
        docker network rm selenium-grid || true

    - name: Create Selenium Grid Network
      run: |
        docker network create selenium-grid

    - name: Start Selenium Grid
      run: |
        docker compose down || true  # Ensure any existing containers are stopped
        docker compose up -d selenium-hub chrome
        
        # Wait for Grid to be ready
        timeout 90s bash -c '
          while ! curl -s http://localhost:4444/wd/hub/status > /dev/null; do 
            echo "Waiting for Selenium Grid to be ready...";
            sleep 5;
          done
        '

    - name: Run tests
      run: |
        mkdir -p test-results
        docker compose run --rm test-runner

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results
        retention-days: 5

    - name: Print logs on failure
      if: failure()
      run: |
        docker compose logs selenium-hub
        docker compose logs chrome
        docker compose logs test-runner

    - name: Cleanup
      if: always()
      run: |
        docker compose down
        docker network rm selenium-grid || true