name: CI with Selenium Grid

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily run at midnight UTC

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

env:
  PYTHON_VERSION: '3.10'
  DOCKER_COMPOSE_VERSION: 'v2.24.1'
  SELENIUM_GRID_URL: 'http://selenium-hub:4444/wd/hub'
  TEST_RESULTS_DIR: 'test-results'

jobs:
  test:
    uses: ./.github/workflows/test-job.yml
    secrets: inherit