name: Selenium Grid Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        mkdir -p test-results

    - name: Set up Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Clean up existing Docker resources
      run: |
        docker system prune -af
        docker network prune -f
        docker compose down --remove-orphans || true

    - name: Create Selenium Grid Network
      run: |
        docker network create selenium-grid || true

    - name: Start Selenium Grid
      run: |
        docker compose up -d selenium-hub chrome
        
        echo "Waiting for Selenium Grid to be ready..."
        timeout=180
        start_time=$(date +%s)
        
        while true; do
          if curl -sSL http://localhost:4444/wd/hub/status | grep -q "\"ready\": true"; then
            echo "Selenium Grid is ready!"
            break
          fi
        
          current_time=$(date +%s)
          elapsed=$((current_time - start_time))
        
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for Selenium Grid"
            docker compose logs
            exit 1
          fi
        
          echo "Still waiting... ($elapsed seconds elapsed)"
          sleep 5
        done

    - name: Run tests
      run: |
        mkdir -p test-results
        chmod 777 test-results  # Ensure directory is writable
        
        # Run tests with proper user mapping
        docker compose run --rm \
          -u $(id -u):$(id -g) \
          test-runner || {
            echo "Tests failed"
            exit 1
          }

    - name: Print logs on failure
      if: failure()
      run: |
        echo "Selenium Hub Logs:"
        docker compose logs selenium-hub
        echo -e "\nChrome Node Logs:"
        docker compose logs chrome
        echo -e "\nTest Runner Logs:"
        docker compose logs test-runner 

    - name: Slack Notification
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Workflow failed!'
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Changed from SLACK_WEBHOOK to SLACK_WEBHOOK_URL

    - name: Clean up existing Docker resources
      run: docker compose down --volumes --remove-orphans || true