name: Selenium Grid Tests

on:
  push:
    branches: [ main, master ]  # Added master branch
  pull_request:
    branches: [ main, master ]  # Added master branch
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'sanity'
        type: choice
        options:
          - sanity
          - regression
          - all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Create network
      run: docker network create grid

    - name: Start Selenium Grid
      run: |
        docker-compose up -d
        echo "Waiting for Grid to be ready..."
        sleep 15

    - name: Check Grid status
      run: |
        docker ps -a
        curl -s http://localhost:4444/wd/hub/status || true

    - name: Run tests
      env:
        PYTHONPATH: ${GITHUB_WORKSPACE}
      run: |
        if [ "${{ github.event.inputs.test_suite }}" = "sanity" ]; then
          pytest -v -m "sanity" tests/ui/ --html=test-results/report.html
        elif [ "${{ github.event.inputs.test_suite }}" = "regression" ]; then
          pytest -v -m "regression" tests/ui/ --html=test-results/report.html
        else
          pytest -v tests/ui/ --html=test-results/report.html
        fi

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results

    - name: Print logs on failure
      if: failure()
      run: docker-compose logs

    - name: Stop Selenium Grid
      if: always()
      run: docker-compose down