name: Upload Artifacts

on:
  workflow_call:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ${{ env.TEST_RESULTS_DIR }}/
          retention-days: 30