name: Upload Coverage

on:
  workflow_call:

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          file: ${{ env.TEST_RESULTS_DIR }}/coverage.xml
          fail_ci_if_error: false